### ISSUE TITLE
.container's max-width is not $max-width

### ISSUE THREAD

**Issue by andimal** [kohactive/manhattan#7]
variable "set" [here](https://github.com/kohactive/manhattan/blob/master/app/assets/stylesheets/manhattan/_variables.css.sass#L9)

.container result:
![image](https://f.cloud.github.com/assets/813528/2350917/79fcfaf6-a576-11e3-9dc4-01b6622d46bf.png)

**Comment by johnkoht** [comment]
Hey @andimal `$max-width` in manhattan actually sets the `$max-width` variable in Bourbon Neat, see this: http://thoughtbot.github.io/neat-docs/latest/#max-width

**Comment by andimal** [comment]
Not with that `!default` it doesn't!

**Comment by andimal** [comment]
I believe the problem here was that the variables file was being included _after_ manhattan, leading to manhattan not having the locally-set `$max-width` variable. Import the variables file first and voilà.
